### PR TITLE
feat: update codebase to reflect the latest configuration in the parent open-sdg-data project

### LINKED ISSUE #42: Resolve deprecation notices and add github environments
### Problem
There are multiple github actions workflow deprecation notices in our current deployments. We would also like to add Environments to the repository for dev and prod.  

### Proposed Solution
resolve deprectations by updating the actions similar to https://github.com/CityOfLosAngeles/calendar-embed/pull/68.

### LINKED ISSUE #44: Update codebase to align w/ latest configuration of the parent project
### Problem

The [open-sdg-data-starter](https://github.com/open-sdg/open-sdg-data-starter) template repository has been update significantly. This repository will need to have applicable changes made to be up to date what's included on the template.

### Solution

Refer to the updated template and update the codebase here as needed considering our unique configuration.
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by jaylenw**
### What does this PR do?

- Add GitHub Issue & PR Templates
- Update configuration files to reflect the needs of the project and that were provided in https://github.com/open-sdg/open-sdg-data-starter/tree/20bd3b299b3917b18a1a2ade8cf8344d5f130d99
- Remove Prose.io support for now
- Update GitHub Action workflow files to support build, verification, and deployment.

### Background info

- Changes in branch ghi-42 were squashed and merged into this branch
- @naomiikd and @kerrylacity , please take a look at https://github.com/CityOfLosAngeles/open-sdg-data-starter/issues/44#issuecomment-1977617949. A GitHub issue should be created to resolve the duplication issue
- I determined VS Code Dev Containers were the best tool for us to get a local dev environment configured so configuration files and documentation has been provided pertaining to this.
- A GitHub Issue will be created for this repository to trigger the appropriate workflows in the open-sdg-site-starter repo on successful deployment. See #47
- A GitHub Issue will be created to evaluate if we need to fork the Python dependency found here https://github.com/dougmet/yamlmd. See #46 

#### Provide manual tests steps if applicable

Setup the local development environment as documented in the `README.md`. Run the the commands for verifying and building the site.

#### Provide steps for running automated tests if applicable

N/A

### Which issue(s) is/are related to this PR?

This PR is/are related to issue(s) #42  and #44

close #42 
close #44 
close #41 
close #43

### CODE REVIEW

**Review by RV-LACity — DISMISSED** [review]

**Review by naomiikd — DISMISSED** [review]

**Comment by jaylenw** [comment]
@naomiikd @kerrylacity , a part of the approval process, please make sure the instructions for setting up the local dev environment and running the commands I've documented works for you two 😄 . Let me know if it doesn't and we can see if I need to update the documentation.

**Comment by jaylenw** [comment]
@naomiikd let me know if these changes are good, see https://github.com/CityOfLosAngeles/open-sdg-data-starter/pull/45/commits/0480ca07296ca69d3a5353ddc4104bba23bd0992

**Comment by naomiikd** [comment]
@jaylenw  Those changes look perfect! Thank you.

**Review by naomiikd — DISMISSED** [review]

**Comment by jaylenw** [comment]
@RV-LACity @naomiikd @kerrylacity , by working on the sdg-site-starter repo, I have updated the `requirements.txt` and config setting for translations as mentioned in https://github.com/open-sdg/open-sdg/releases/tag/2.3.0. Reviews have been requested again.

**Review by naomiikd — APPROVED** [review]

**Comment by jaylenw** [comment]
Updated PR description to close #41 & close #43

**Review by kerrylacity — APPROVED** [review]

**Review by RV-LACity — APPROVED** [review]

**Pull request merged**
